package core

import (
	"bytes"
	"encoding/hex"
	"errors"
	apiv1 "github.com/pqabelian/abec/sdkapi/v1"
	api "github.com/pqabelian/abec/sdkapi/v2"
	"os"
	"sort"
)

// Define constants.
const (
	DEFAULT_CHAIN_ID = MainNet
)

// Define util functions.
func GetRingBlockHeights(height int64) []int64 {
	firstRingBlockHeight := height - height%3
	ringBlockHeights := []int64{firstRingBlockHeight, firstRingBlockHeight + 1, firstRingBlockHeight + 2}
	return ringBlockHeights
}

// Define the CryptoKey data type.
type CryptoKey struct {
	Bytes
}

// Define methods for CryptoKey.
func NewCryptoKey(data Bytes) *CryptoKey {
	return &CryptoKey{Bytes: data}
}

// CryptoKeysAndAddress represents an address key pair generated by calling following methods:
// - GenerateCryptoKeysAndAddressByRootSeeds
// - GenerateCryptoKeysAndAddressByRandSeeds
// - GenerateCryptoKeysAndAddressByRootSeedsFromPublicRand
// in where, DetectorKey is added for new types of address
type CryptoKeysAndAddress struct {
	SpendSecretKey    CryptoKey
	SerialNoSecretKey CryptoKey
	ViewSecretKey     CryptoKey
	DetectorKey       CryptoKey // added when version 2
	CryptoAddress     CryptoAddress
}

// GenerateSafeCryptoSeed generate safe crypto seed from scratch
//
// Deprecated: use GenerateSeed
func GenerateSafeCryptoSeed() (Bytes, error) {
	cryptoSeeds, err := GenerateSeed(CryptoSchemePQRingCT, PRIVACY_LEVEL_FULL_PRIVACY_PRE)
	if err != nil {
		return nil, err
	}
	return cryptoSeeds.Bytes()
}

// GenerateCryptoKeysAndAddress generate crypto key and address from specified crypto seed
//
// Deprecated: use GenerateCryptoKeysAndAddressByRandSeeds
func GenerateCryptoKeysAndAddress(cryptoSeed Bytes) (*CryptoKeysAndAddress, error) {
	return GenerateCryptoKeysAndAddressByRandSeeds(cryptoSeed)
}

// DecodeCoinAddressFromTxOutData decode coin address from transaction output data
//
// Deprecated: ONLY be used for full-privacy address, for all types, use DecodeCoinAddressFromSerializedTxOutData
func DecodeCoinAddressFromTxOutData(txOutData Bytes) (*CoinAddressFullPrivacyPre, error) {
	coinAddressData, err := DecodeCoinAddressFromSerializedTxOutData(1, txOutData)
	if err != nil {
		return nil, err
	}

	if coinAddressFullPrivacyPre, ok := coinAddressData.(*CoinAddressFullPrivacyPre); ok {
		return coinAddressFullPrivacyPre, nil
	}

	// should not happen, but avoid error, return a impossible value for back-compatible
	return NewCoinAddressFullPrivacyPre(MakeBytes(COIN_ADDRESS_LENGTH_FULL_PRIVACY_PRE)), nil
	//return nil, errors.New("incompatible")
}

// DecodeValueFromTxOutData decode value from transaction output data
//
// Deprecated: use DecodeValueFromTxOutDataByKeys
func DecodeValueFromTxOutData(txOutData Bytes, viewSecretKey *CryptoKey) (int64, error) {
	// api.ExtractCoinValueFromSerializedTxOut will clear up the view secret key param.
	// Thus we pass a copy of the view secret key to avoid this side effect.
	cryptoAddress, err := recoverCryptoAddress(txOutData, viewSecretKey)
	if err != nil {
		return 0, errors.New("failed to recover crypto address")
	}
	viewSecretKeyData := make([]byte, viewSecretKey.Len())
	copy(viewSecretKeyData, viewSecretKey.Bytes)

	value, err := DecodeValueFromTxOutDataByKeys(txOutData, cryptoAddress, NewCryptoKey(viewSecretKeyData))
	if err != nil {
		return -1, err
	}

	return int64(value), nil
}

// recoverCryptoAddress Should ONLY be called by DecodeValueFromTxOutData for keep back-compatibility
func recoverCryptoAddress(txOutData Bytes, viewSecretKey *CryptoKey) (*CryptoAddress, error) {
	// Compatible processing under helpless choice, based on view public key information
	// contained in the existing view secret key
	serializedCryptoScheme := SerializeCryptoScheme(CryptoSchemePQRingCT)
	viewSecretKeyLen := viewSecretKey.Len()
	if viewSecretKeyLen < len(serializedCryptoScheme) {
		return nil, errors.New("invalid view secret key")
	}
	if !bytes.Equal(serializedCryptoScheme, viewSecretKey.Slice()[:len(serializedCryptoScheme)]) {
		return nil, errors.New("unsupported view secret key")
	}
	if viewSecretKeyLen <= 2344 { // hard code here
		return nil, errors.New("invalid view secret key")
	}
	extractViewPublicKeyData := make([]byte, 1188)
	copy(extractViewPublicKeyData[:4], viewSecretKey.Slice()[len(serializedCryptoScheme):len(serializedCryptoScheme)+4])
	copy(extractViewPublicKeyData[4:], viewSecretKey.Slice()[1160:2344])

	coinAddress, err := DecodeCoinAddressFromSerializedTxOutData(1, txOutData)
	if err != nil {
		return nil, errors.New("can not extract coin address from serialized transaction output")
	}

	// recover crypto address
	cryptoAddressData := make([]byte, 0, CryptoSchemeSerializeSize()+len(coinAddress.Data())+len(extractViewPublicKeyData))
	cryptoAddressData = append(cryptoAddressData, serializedCryptoScheme...)
	cryptoAddressData = append(cryptoAddressData, coinAddress.Data()...)
	cryptoAddressData = append(cryptoAddressData, extractViewPublicKeyData...)
	return NewCryptoAddress(cryptoAddressData), nil
}

// GenerateUnsignedRawTx make an unsigned transaction,
// which can be signed with singer key by calling GenerateSignedRawTx
func GenerateUnsignedRawTx(txDesc *TxDesc) (*UnsignedRawTx, error) {
	// Prepare outPointsToSpend.
	outPointsToSpend := make([]*api.OutPoint, 0, len(txDesc.TxInDescs))
	for i := 0; i < len(txDesc.TxInDescs); i++ {
		txidStr := hex.EncodeToString(txDesc.TxInDescs[i].TxHash)
		outPoint, err := api.NewOutPointFromTxIdStr(txidStr, txDesc.TxInDescs[i].TxOutIndex)
		if err != nil {
			return nil, err
		}
		outPointsToSpend = append(outPointsToSpend, outPoint)
	}

	// Prepare serializedBlocksForRingGroup.
	serializedBlocksForRingGroup := getSerializedBlocksForRingGroup(txDesc.TxRingBlockDescs)

	// Prepare txRequestOutputDesc.
	txRequestOutputDescs := make([]*api.TxRequestOutputDesc, 0, len(txDesc.TxOutDescs))
	for i := 0; i < len(txDesc.TxOutDescs); i++ {
		cryptoAddressData := txDesc.TxOutDescs[i].AbelAddress.GetCryptoAddress().Data()
		coinValue := uint64(txDesc.TxOutDescs[i].CoinValue)
		txRequestOutputDesc := api.NewTxRequestOutputDesc(cryptoAddressData, coinValue)
		txRequestOutputDescs = append(txRequestOutputDescs, txRequestOutputDesc)
	}

	// Call API to build the serializedTxRequestDesc.
	serializedTxRequestDesc, err := api.BuildTransferTxRequestDescFromBlocks(
		outPointsToSpend,
		serializedBlocksForRingGroup,
		txRequestOutputDescs,
		uint64(txDesc.TxFee),
		txDesc.TxMemo,
	)
	if err != nil {
		return nil, err
	}

	// Create an unsigned raw tx and return it.
	signers := make([]*ShortAbelAddress, 0, len(txDesc.TxInDescs))
	for _, txInDesc := range txDesc.TxInDescs {
		signers = append(signers, txInDesc.Owner)
	}

	return NewUnsignedRawTx(serializedTxRequestDesc, signers), nil
}

func GenerateSignedRawTx(unsignedRawTx *UnsignedRawTx, signerKeys []*CryptoKeysAndAddress) (*SignedRawTx, error) {
	switchToVersion1, _ := os.LookupEnv("ABELIAN_SDK_SWITCH_TX_OLD_VERSION")
	if switchToVersion1 == "" {
		accounts := make([]Account, len(signerKeys))
		for i := 0; i < len(signerKeys); i++ {
			accounts[i] = NewCryptoKeysAccount(
				&signerKeys[i].SpendSecretKey,
				&signerKeys[i].SerialNoSecretKey,
				&signerKeys[i].ViewSecretKey,
				&signerKeys[i].DetectorKey,
				&signerKeys[i].CryptoAddress,
			)
		}

		return GenerateSignedRawTxV2(unsignedRawTx, accounts)
	}

	// Prepare cryptoKeys.
	cryptoKeys := make([]*apiv1.CryptoKey, 0, len(signerKeys))
	for i := 0; i < len(signerKeys); i++ {
		cryptoKeys = append(cryptoKeys, apiv1.NewCryptoKey(
			signerKeys[i].CryptoAddress.Data(),
			signerKeys[i].SpendSecretKey.Bytes,
			signerKeys[i].SerialNoSecretKey.Bytes,
			signerKeys[i].ViewSecretKey.Bytes))
	}

	// Call API to create the signed raw tx.
	serializedTxFull, txid, err := apiv1.CreateTransferTx(unsignedRawTx.Bytes, cryptoKeys)
	if err != nil {
		return nil, err
	}

	// Create a signed raw tx and return it.
	// NOTE: The txid used by the RPC/SDK/UI is a reversed version of the txid used by the API.
	reversedTxid := make([]byte, len(txid))
	for i := 0; i < len(txid); i++ {
		reversedTxid[i] = txid[len(txid)-i-1]
	}

	return NewSignedRawTx(serializedTxFull, AsBytes(reversedTxid)), nil
}

func DecodeCoinSerialNumbers(coinIDs []*CoinID, serialNoSecretKeys []*CryptoKey, ringBlockDescs map[int64]*TxBlockDesc) ([]Bytes, error) {
	// Convert serial numbers to Bytes type and return them.
	coinSerialNumbers := make([]Bytes, len(coinIDs))
	for i := 0; i < len(serialNoSecretKeys); i++ {
		viewAccount := NewCryptoKeyViewAccount(
			serialNoSecretKeys[i],
			nil,
			nil,
			nil,
		)
		serialNumbers, err := viewAccount.GenerateSerialNumbers([]*CoinID{coinIDs[i]}, ringBlockDescs)
		if err != nil {
			return nil, err
		}
		if len(serialNumbers) != 1 {
			return nil, errors.New("incompatible")
		}
		coinSerialNumbers[i] = serialNumbers[0]
	}

	return coinSerialNumbers, nil
}

func getSerializedBlocksForRingGroup(ringBlockDescs map[int64]*TxBlockDesc) [][]byte {
	heights := make([]int64, 0, len(ringBlockDescs))
	for height := range ringBlockDescs {
		heights = append(heights, height)
	}

	sort.Slice(heights, func(i, j int) bool {
		return heights[i] < heights[j]
	})

	serializedBlocksForRingGroup := make([][]byte, 0, len(ringBlockDescs))
	for i := 0; i < len(heights); i++ {
		serializedBlocksForRingGroup = append(serializedBlocksForRingGroup, ringBlockDescs[heights[i]].BinData)
	}

	return serializedBlocksForRingGroup
}
